### ISSUE TITLE
Problem with 3.0.1 and XF 4.0 (Android) - Method not found: void ModernHttpClient.NativeMessageHandler..ctor()

### ISSUE THREAD

**Issue by remmettaro** [alexrainman/ModernHttpClient#27] opened 2019-05-28 22:33 UTC
The first time that I generate an instance of HTTPClient I receive this error, it works with 2.7.2

**Comment by alexrainman** [comment] 2019-05-28 22:36
Mmmm interesting. Let me try to reproduce it.

**Comment by xamarindevelopervietnam** [comment] 2019-05-29 05:01
same issue on XF 3.6 as well

**Comment by ChrisJAult** [comment] 2019-05-29 06:39
Same issue here XF 3.6 tested on Android 8.0

**Comment by acaliaro** [comment] 2019-05-29 13:07
Same with XF 4 and Android 6

**Comment by xamarindevelopervietnam** [comment] 2019-05-29 15:46
should be fixed via this pull request https://github.com/alexrainman/ModernHttpClient/pull/28

**Closed** 2019-05-29 19:25 UTC
Labels: bug

**Comment by xamarindevelopervietnam** [comment] 2019-05-30 02:05
I know you did the same thing but with an open source project, we should merge pull request of the other contributors @alexrainman

**Comment by alexrainman** [comment] 2019-05-30 02:10
I took this project after being abandonware for two years. I did it because i wanted to help the community and because i wanted to so, i decide if i merge pull requests or not.

**Comment by xamarindevelopervietnam** [comment] 2019-05-30 02:15
sure @alexrainman keep it up, we very happy to use this project. If you remember, I've supported and talked with you when you started this project.

**Comment by alexrainman** [comment] 2019-05-30 02:17
I really appreciate the support. Thanks

**Comment by xamarindevelopervietnam** [comment] 2019-05-30 02:18
uw!
