### ISSUE TITLE
Exception on UWP with Xamarin Forms

### ISSUE THREAD

**Issue by pfranklinExponent** [alexrainman/ModernHttpClient#3] opened 2018-02-07 23:21 UTC
I receive the following exception when using the ModernHttpClient in the .NET Standard library when running a UWP app:

_Could not load type 'ModernHttpClient.NativeMessageHandler' from assembly 'ModernHttpClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'_

However, if I instantiate the client and run the code locally within the UWP project it works fine.  I'd like to put all my services, etc. in the .NET Standard library, but this is preventing me from doing so.

All works fine in iOS.  I have yet to test on Android

**Comment by alexrainman** [comment] 2018-02-13 15:12
The plugin only support .Net Standard 2.0, is that your case?

**Comment by pfranklinExponent** [comment] 2018-02-13 16:47
Yes, I'm using .Net Standard 2.0.  Not sure if this helps or not, but I removed this plugin and replaced it with the original ModernHttpClient written by Paul Betts and everything works fine across all platforms (iOS, Android, and UWP).  I was under the assumption that the original did not support .Net Standard, which was why I went with your plugin.

**Comment by alexrainman** [comment] 2018-02-13 16:56
No idea how it is working and why mine is not working in your case because it is working for others. Mine supports .Net Standard but also it comes with a custom implementation for UWP.

**Comment by alexrainman** [comment] 2018-02-13 17:28
As i said, theres a custom native handler for UWP that is not included in the original plugin. That custom handler implements lot of things: timeout, native cookie handler, support for self signed certificates and so on.

**Comment by Umar3x** [comment] 2018-02-18 23:28
Hello,
First of all, thank you @alexrainman for your work on updating this package.
I got the exact same problem for UWP. Same error. 

Tested and working well on Android and iOS. I'm also targeting .net standard 2.0.

**Comment by Pinox** [comment] 2018-02-25 15:02
@alexrainman  As previous 2 users stated.  I also get the same error by just installing moderHttp in clean XF template.

Error message : TypeLoadException: Could not load type 'ModernHttpClient.NativeMessageHandler' from assembly 'ModernHttpClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Please find attached a **repo** that reproduce the problem, Android works perfectly but UWP throws an exception on the same code.

Thanks in advance for looking at this.

[modernHttp.zip](https://github.com/alexrainman/ModernHttpClient/files/1756184/modernHttp.zip)

**Comment by alexrainman** [comment] 2018-02-25 16:03
@pinox going to take a look.

**Comment by Pinox** [comment] 2018-02-25 17:16
@alexrainman Thanks.  As a side note, not sure if this can help you or if it's applicable to this problem at all, but I recently listened to an interesting podcast by james montemagno specifically for library creators. http://www.mergeconflict.fm/85   called multi-targeting and the complexity of nuget packages.

**Comment by alexrainman** [comment] 2018-02-26 15:01
I really don't know what is going on here. It works on the Demo but not in Nuget package :(

**Comment by alexrainman** [comment] 2018-04-24 13:05
Trying to solve this and release a new version.

**Comment by alexrainman** [comment] 2018-05-07 13:46
Going to fix this in the next release.

**Comment by alexrainman** [comment] 2018-05-10 19:56
Version 2.7.0 has been released. Please test.

**Comment by Pinox** [comment] 2018-05-10 20:58
Hi Alex,

I still see a error on the sample project posted above after updating to version 2.7

![modernhttperror](https://user-images.githubusercontent.com/5297255/39893903-900231b2-54a5-11e8-9b32-f5c219fb7a41.PNG)

**Comment by Pinox** [comment] 2018-05-18 11:36
Hi Alex, 

I see with this lib using multi-targeting now , not sure if this is of use for you.

https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/?utm_campaign=Weekly%2BXamarin&utm_medium=email&utm_source=Weekly_Xamarin_156

**Comment by alexrainman** [comment] 2018-05-18 17:12
Somehow the plugin is not working as expected in .netstandard with the original architecture from Paul. Going to migrate it to default Xamarin plugin Lazy load style.

**Comment by alexrainman** [comment] 2018-05-19 23:48
Found a lot of issues in my custom HttpClientHandler for UWP that i didn't see before. Fixed now.

**Closed by alexrainman** 2018-05-19 23:48 UTC
Labels: bug

**Comment by Pinox** [comment] 2018-05-20 07:44
Awesome @alexrainman  I changed the code in the sample to be exactly the same just to make sure we compare apples with apples with default httpclient.


  private async void BtnGetModernHttp_Clicked(object sender, EventArgs e)
        {
            
        // ... Target page.
        string page = "http://en.wikipedia.org/";

            // ... Use HttpClient.
            using (HttpClient client = new HttpClient())
            using (HttpResponseMessage response = await modernhttpClient.GetAsync(page))
            using (HttpContent content = response.Content)
            {
                // ... Read the string.
                string result = await content.ReadAsStringAsync();

                // ... Display the result.
                if (result != null &&
                    result.Length >= 50)
                {
                    Debug.WriteLine(result.Substring(0, 150) + "...");

                    await DisplayAlert("Reply", result.Substring(0, 150).ToString(), "OK");

                }
            }

        }

        private async void BtnGetHttp_Clicked(object sender, EventArgs e)
        {


            // ... Target page.
            string page = "http://en.wikipedia.org/";

            // ... Use HttpClient.
            using (HttpClient client = new HttpClient())
            using (HttpResponseMessage response = await client.GetAsync(page))
            using (HttpContent content = response.Content)
            {
                // ... Read the string.
                string result = await content.ReadAsStringAsync();

                // ... Display the result.
                if (result != null &&
                    result.Length >= 50)
                {
                    Debug.WriteLine(result.Substring(0, 150) + "...");

                    await DisplayAlert("Reply", result.Substring(0, 150).ToString(), "OK");

                }
            }
        }



On the first click of modernHttpClient it works as expected , on the second click I now get a different error 

![new error](https://user-images.githubusercontent.com/5297255/40276738-3bd72d4e-5c12-11e8-8575-cec3a88ef300.PNG)

**Comment by alexrainman** [comment] 2018-05-20 13:46
Great!
